theme: jekyll-theme-cayman
title: Copilot Experience Lab
description: Microsoft Copilot Experience Labs
repository: miookawa/copilot-experience-lab

plugins:
  - jekyll-optional-front-matter
  - jekyll-default-layout
  - jekyll-relative-links
  - jekyll-github-metadata
  - jekyll-titles-from-headings

optional_front_matter:
  remove_originals: true

defaults:
  - scope:
      path: "contents"
      type: "pages"
    values:
      strip_title: true
  - scope:
      path: "contents/README.md"
      type: "pages"
    values:
      strip_title: false
